server:
  port: 8060
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Password12
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
  application:
    name: order-service
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka